export const SET_DATA = '@FEATURE/STORE/SET_DATA';
export const REMOVE_DATA = '@FEATURE/STORE/REMOVE_DATA';
export const ROUTE = 'ROUTE';
export const NOTIFY = 'NOTIFY';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';